version: 0.0
os: linux

hooks:
  ApplicationStop:
      # to stop previously running app container (if it was already deployed) bcoz it will contradict with new coming container on port no. as that will be same
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
